name = "onyx-engine"
main = "src/index.ts"
compatibility_date = "2024-04-05"

[vars]
ENVIRONMENT = "dev"
DATA_SOURCE = "local" # or "r2"

# [r2_buckets]
# binding = "ONYX_BUCKET"
# bucket_name = "onyx-data"
